version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
    - "23306:3306/tcp"

  mariadb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
    - "23307:3306/tcp"

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: rootpass
    ports:
    - "25432:5432/tcp"
